# Borders
bordercolor=0x928374ff
focuscolor=0xEBDBB2ff
urgentcolor=0xad401fff

# Background
# gruvbox bg: 0x282828
rootcolor=0x282828ff

# Drag-to-tile preview
dropcolor=0x8FBA7C55
splitcolor=0xEB441EFF

# Window states (mango defaults)
maximizescreencolor=0x89aa61ff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff
